### ISSUE TITLE
Module '"nativescript-push"' has no exported member 'messaging'.ts(2305)

### ISSUE THREAD

**Issue by zeejay09** [nativescript-community/nativescript-push#4]
Typescript says "Module '"nativescript-push"' has no exported member 'messaging'.ts(2305)"

I am using nativescript + angular

Error in console says:

```
export 'messaging' (imported as 'messaging') was not found in 'nativescript-push' (possible exports: __esModule, areNotificationsEnabled, getCurrentPushToken, init, onAppModuleLaunchEvent, onAppModuleResumeEvent, registerForInteractivePush, registerForPushNotifications, subscribeToTopic, unregisterForPushNotifications, unsubscribeFromTopic)
```

**Comment by farfromrefug** [comment]
@zeejay09 you ll have to give more details... versions, tsconfig.
next time please be more detailed so we can help you

**Comment by zeejay09** [comment]
I just created a new nativescript-angular app via cli and installed this package then tried to use it and error above occurs, anyway closing this as I opt to install the whole nativescript-plugin-firebase instead just to use the non firebase messaging.
